// Mocks generated by Mockito 5.4.5 from annotations
// in dhan_saarthi/test/feature/fund_details/presentation/bloc/mock_get_details.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:dhan_saarthi/core/failure.dart' as _i6;
import 'package:dhan_saarthi/feature/fund_detail/domain/enitiies/fund_details_entity.dart'
    as _i7;
import 'package:dhan_saarthi/feature/fund_detail/domain/respository/fund_details_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

import 'mock_get_details.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFundDetailsRepository_0 extends _i1.SmartFake
    implements _i2.FundDetailsRepository {
  _FakeFundDetailsRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FundDetails].
///
/// See the documentation for Mockito's code generation for more information.
class MockFundDetails extends _i1.Mock implements _i4.FundDetails {
  MockFundDetails() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FundDetailsRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeFundDetailsRepository_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.FundDetailsRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.FundDetailsEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<
              _i3.Either<_i6.Failure, _i7.FundDetailsEntity>
            >.value(
              _FakeEither_1<_i6.Failure, _i7.FundDetailsEntity>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.FundDetailsEntity>>);
}
